info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
eureka:
  instance:
    hostname: onecard-provider1
    instance-id: onecard-provider:${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:9001/eureka/,http://eureka-server2:9002/eureka/,http://eureka-server3:9003/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS