server:
  port: 9022
spring:
  application:
    name: school-provider-cluster
  profiles:
    active: dev

#apollo配置
app:
  id: ${spring.application.name}
apollo:
  meta: http://47.107.255.252:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application

#日志
logging:
  config: classpath:logback-spring.xml