info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
server:
  port: 9022
spring:
  application:
    name: school-provider-cluster
  profiles:
    active: dev
  #spring框架时间比京八区标准时间差八小时(time-zone一定不能少，否则熔断出问题！！！！切记切记) Kang
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#apollo配置
app:
  id: school-provider-cluster1
apollo:
  meta: http://47.107.255.252:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: BASE.public.eureka,BASE.public-hikari-ds,application,BASE.public-rocketmq
    #BASE.public-redis,:

redis:
  nodes: 119.23.185.109:8001,47.107.253.90:8003,47.107.255.252:8005,119.23.185.109:8002,47.107.253.90:8004,47.107.255.252:8006
  commandTimeout: 10000  #redis操作的超时时间
  maxTotal: 5000 #最大连接数
  maxIdle: 30 #最大空闲连接数
  minIdle: 5 #最小空闲连接数
  maxWait: 3000  #获取连接最大等待时间 ms  #default -1

#日志
logging:
  config: classpath:logback-spring.xml