info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
spring:
  application:
    name: school-provider-cluster
  profiles:
    active: dev

#apollo配置
app:
  id: school-provider-cluster1
apollo:
  meta: http://47.107.255.252:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application,BASE.public-hikari-ds,BASE.public-redis,BASE.public.eureka

#日志
logging:
  config: classpath:logback-spring.xml