info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
eureka:
  instance:
    hostname: wallet-provider1
    instance-id: wallet-provider:${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:9001/eureka/,http://eureka-server2:9002/eureka/,http://eureka-server3:9003/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
#数据源配置
spring:
  datasource:
    ds0:
      name : dataSource
      url : jdbc:mysql://119.23.185.109:3306/bdxh_wallet?characterEncoding=utf-8&failOverReadOnly=false&autoReconnect=true&roundRobinLoadBalance=true
      username : admin
      password : Abc_123456
      type : com.alibaba.druid.pool.DruidDataSource
      driver-class-name : com.mysql.jdbc.Driver
      filters :  stat
      maxActive : 20
      initialSize : 1
      minIdle : 3
      maxWait : 60000
      timeBetweenEvictionRunsMillis : 60000
      minEvictableIdleTimeMillis : 300000
      validationQuery : select 'x' from dual
      testWhileIdle : true
      testOnBorrow : false
      testOnReturn : false
      poolPreparedStatements : true
      maxOpenPreparedStatements : 50
      connectionProperties: {druid.stat.mergeSql: true,druid.stat.slowSqlMillis: 5000}
#ID生成器
id-generator:
  workerId: 0
  datacenterId: 0