server:
  port: 9001
spring:
  application:
    name: eureka-server-cluster
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: bdxh123456
      #忽略springboot 监控的路径
    basic:
      path: /actuator
