info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
#端口
server:
  port: 9032
spring:
  application:
    name: task-provider-cluster
  profiles:
    active: dev
    #spring框架时间比京八区标准时间差八小时(time-zone一定不能少，否则熔断出问题！！！！切记切记) Kang
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: '47.107.253.90:9876;47.107.255.252:9876 '
rocketmq:
  producer:
    defaultName: default-task-provider
    transEnable: true
    transName: trans-task-provider
#apollo配置
app:
  id: task-provider-cluster1
apollo:
  meta: http://47.107.255.252:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: BASE.public.eureka,application,BASE.public-redis

logging:
  config: classpath:logback-spring.xml
