info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
eureka:
  instance:
    hostname: zuul-gateway1
    instance-id: gateway-instance:${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:9001/eureka/,http://eureka-server2:9002/eureka/,http://eureka-server3:9003/eureka/
zuul:
  routes:
    api-a:
      path: /demo/** #网关地址
      serviceId: demo-provider #代理到对应的服务
    api-b:
      path: /wallet/** #网关地址
      serviceId: wallet-provider-cluster #代理到对应的服务